### ISSUE TITLE
How to edit qmpy/db/settings?

### ISSUE THREAD

**Issue by lmj1029123** [wolverton-research-group/qmpy#90]
Hi,

I am trying to use the OQMD database. I have installed it and set up the database such that I got the following: 
mysql> select count(*) from entries;
+----------+
| count(*) |
+----------+
|   173653 |
+----------+

However, when I use qmpy in python and run:

`>>> fe = Element.objects.get(symbol='Fe')`

I got 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mingjieliu/anaconda3/envs/qmpy_env/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/mingjieliu/anaconda3/envs/qmpy_env/lib/python2.7/site-packages/django/db/models/query.py", line 328, in get
    num = len(clone)
  File "/Users/mingjieliu/anaconda3/envs/qmpy_env/lib/python2.7/site-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/Users/mingjieliu/anaconda3/envs/qmpy_env/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/mingjieliu/anaconda3/envs/qmpy_env/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/Users/mingjieliu/anaconda3/envs/qmpy_env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 829, in execute_sql
    sql, params = self.as_sql()
  File "/Users/mingjieliu/anaconda3/envs/qmpy_env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 387, in as_sql
    where, w_params = self.compile(self.query.where)
  File "/Users/mingjieliu/anaconda3/envs/qmpy_env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 357, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/Users/mingjieliu/anaconda3/envs/qmpy_env/lib/python2.7/site-packages/django/db/models/sql/where.py", line 104, in as_sql
    sql, params = compiler.compile(child)
  File "/Users/mingjieliu/anaconda3/envs/qmpy_env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 357, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/Users/mingjieliu/anaconda3/envs/qmpy_env/lib/python2.7/site-packages/django/db/models/lookups.py", line 218, in as_sql
    lhs_sql, params = self.process_lhs(compiler, connection)
  File "/Users/mingjieliu/anaconda3/envs/qmpy_env/lib/python2.7/site-packages/django/db/models/lookups.py", line 211, in process_lhs
    db_type = self.lhs.output_field.db_type(connection=connection)
  File "/Users/mingjieliu/anaconda3/envs/qmpy_env/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 614, in db_type
    return connection.data_types[self.get_internal_type()] % data
  File "/Users/mingjieliu/anaconda3/envs/qmpy_env/lib/python2.7/site-packages/django/utils/functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/mingjieliu/anaconda3/envs/qmpy_env/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 196, in data_types
    if self.features.supports_microsecond_precision:
  File "/Users/mingjieliu/anaconda3/envs/qmpy_env/lib/python2.7/site-packages/django/utils/functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/mingjieliu/anaconda3/envs/qmpy_env/lib/python2.7/site-packages/django/db/backends/mysql/features.py", line 52, in supports_microsecond_precision
    return self.connection.mysql_version >= (5, 6, 4) and Database.version_info >= (1, 2, 5)
  File "/Users/mingjieliu/anaconda3/envs/qmpy_env/lib/python2.7/site-packages/django/utils/functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/mingjieliu/anaconda3/envs/qmpy_env/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 371, in mysql_version
    with self.temporary_connection():
  File "/Users/mingjieliu/anaconda3/envs/qmpy_env/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/mingjieliu/anaconda3/envs/qmpy_env/lib/python2.7/site-packages/django/db/backends/base/base.py", line 462, in temporary_connection
    cursor = self.cursor()
  File "/Users/mingjieliu/anaconda3/envs/qmpy_env/lib/python2.7/site-packages/django/db/backends/base/base.py", line 162, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/Users/mingjieliu/anaconda3/envs/qmpy_env/lib/python2.7/site-packages/django/db/backends/base/base.py", line 135, in _cursor
    self.ensure_connection()
  File "/Users/mingjieliu/anaconda3/envs/qmpy_env/lib/python2.7/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/Users/mingjieliu/anaconda3/envs/qmpy_env/lib/python2.7/site-packages/django/db/backends/base/base.py", line 118, in connect
    conn_params = self.get_connection_params()
  File "/Users/mingjieliu/anaconda3/envs/qmpy_env/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 263, in get_connection_params
    if settings_dict['HOST'].startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'

It seems that the database is not correctly set up. I noticed that we are supposed to "Set the DATABASES variable such that ‘USER’ is the user with permissions to access the newly installed database." However, I am not very sure how I am supposed to do it. 

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('qmdb_v1_1_name'),
        'USER': os.environ.get('qmdb_v1_1_user'),
        'PASSWORD': os.environ.get('qmdb_v1_1_pswd'),
        'HOST': os.environ.get('qmdb_v1_1_host'),
        'PORT': os.environ.get('qmdb_v1_1_port') 
    }
}

The database in mysql is accessible to mingjieliu@localhost. Should I set 'USER': os.environ.get('qmdb_v1_1_user'), to   'USER': 'mingjieliu', ? Or should I do something else? Do I need to change 'NAME', 'PASSWORD', etc?  

Thank you very much!

Best,
Mingjie

**Comment by tachyontraveler** [comment]
You can,
either define these environment variables (i.e.; qmdb_v1_1_name, qmdb_v1_1_user, etc.) on your `bashrc` file 
or 
edit the DATABASES dictionary in `qmpy/db/settings.py` file to:

DATABASES = {
'default': {
'ENGINE': 'django.db.backends.mysql',
'NAME': _**name of the database**_,
'USER': 'mingjieliu',
'PASSWORD': _**the MySQL user's password**_,
'HOST': localhost _**(unless you've changed the default host)**_,
'PORT': "" _**(of course, unless you've changed the default port)**_
}
}

**Comment by lmj1029123** [comment]
Thanks for the reply. However, I am still getting the same error. 

I tried several things 

DATABASES = {
'default': {
'ENGINE': 'django.db.backends.mysql',
'NAME': 'qmdb',
'USER': 'mingjieliu',
'PASSWORD': '',
'HOST': 'localhost' or localhost,
'PORT': '3306' or ''
}
}

all of those give me the same error. Am I specifying them correctly? Or is there something else that could be wrong. I am using mysql 8.0.18

**Comment by mohanliu** [comment]
can you try this
```python
'HOST': '127.0.0.1'
```
And update `allowed_host` in `qmpy/db/settings.py` to 
```python
ALLOWED_HOSTS = ['127.0.0.1']
```

**Comment by lmj1029123** [comment]
It is still the same error..

**Comment by lmj1029123** [comment]
I downgrade the mysql to 5.7.28 and it works now.
